# -*- coding: utf-8 -*-
"""1. plot scatter

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w3P12l11V52wcZUPwTAtY9WkOZnYSuMc
"""

import numpy as np
import matplotlib.pyplot as plt

data = np.random.rand(1024, 2)
plt.scatter(data[:,0], data[:,1])
plt.show()