# -*- coding: utf-8 -*-
"""plot dari data

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a92ltaIKhs5hvk871OivEr23GABd8ovo
"""

import matplotlib.pyplot as plt
X, Y = [], []
for line in open('file.txt', 'r'):
    nilai = [float(s) for s in line.split()]
    X.append(nilai[0]) #nilai sumbu x
    Y.append(nilai[1]) #nilai sumbu y
plt.plot(X, Y)
plt.title('Data "file.text"')
plt.xlabel('x')
plt.ylabel('y')
plt.show()

import matplotlib.pyplot as plt
with open('file.txt', 'r') as f:
    X, Y = zip(*[[float(s) for s in line.split()] for line in f])
plt.plot(X, Y)
plt.title ('Data "file.text"')
plt.xlabel('x')
plt.ylabel('y')
plt.show()
Footer
© 2022 GitHub, Inc.

import matplotlib.pyplot as plt
import numpy as np

data = np.loadtxt('file.txt')

plt.plot(data[:,0], data[:,1])
plt.title ('Data "file.text"')
plt.xlabel('x')
plt.ylabel('y')
plt.show()