# -*- coding: utf-8 -*-
"""plot line

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JStxiMUsF6c1FMUPg-ONkELaRxUFcMIf
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.arange(-2*np.pi,2*np.pi,0.01)
y = np.sin(3*x)/x
plt.plot(x,y)
plt.show()