# -*- coding: utf-8 -*-
"""plot grafik kurva dalam beberapa

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mlto3ratebrVJ8qKmlqHNN6j1fsjL09R
"""

#plot grafik dalam beberapa figure
import matplotlib.pyplot as plt
import math
import numpy as np

t = np.arange(0,5,0.1)
y1 = np.sin(math.pi*t)
y2 = np.sin(math.pi*t+math.pi/2)
y3 = np.sin(math.pi*t-math.pi/2)

plt.subplot(3,1,1)
plt.title('Fungsi y1')
plt.plot(t,y1,'b--')

plt.subplot(3,1,2)
plt.title('Fungsi y2')
plt.plot(t,y2,'g')

plt.subplot(3,1,3)
plt.title('Fungsi y3')
plt.plot(t,y3,'r-.')


plt.show()

# plot kurva dalam beberapa grafik
import matplotlib.pyplot as plt
import math
import numpy as np
t = np.arange(0,5,0.01)
y1 = np.sin(math.pi*t)
y2 = np.sin(math.pi*t+math.pi/2)
y3 = np.sin(math.pi*t-math.pi/2)
plt.plot(t,y1,'b--',t,y2,'g',t,y3,'r-.')
plt.show()