# -*- coding: utf-8 -*-
"""plot bar

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bwCy6011LyoFRbB_NI77jVE50bJoRZqV
"""

import matplotlib.pyplot as plt
import numpy as np
index = np.arange(5)
values1 = [5,7,3,4,6]
values2 = [6,5,4,5,5]
values3 = [4,6,5,4,6]
bw = 0.3
plt.axis([0,5,0,8])
plt.title('Diagram Batang Multiserial',fontsize=20)
plt.barh(index,values1,bw,color='b')
plt.barh(index+bw,values2,bw,color='g')
plt.barh(index+2*bw,values3,bw,color='r')
plt.yticks(index+1.5*bw,['A','B','C','D','E'])
plt.show()

import matplotlib.pyplot as plt
import numpy as np
series1 = np.array([3,4,5,3])
series2 = np.array([1,2,2,5])
series3 = np.array([2,3,3,4])
index = np.arange(4)
plt.axis([-0.5,3.5,0,15])
plt.title('Diagram Batang Bertumpuk Multiserial')
plt.bar(index,series1,color='r')
plt.bar(index,series2,color='b',bottom=series1)
plt.bar(index,series3,color='g',bottom=(series2+series1))
plt.xticks(index+0.4,['Sep21','Okt21','Nov21','Des21'])
plt.show()

import matplotlib.pyplot as plt
import numpy as np
series1 = np.array([3,4,5,3])
series2 = np.array([1,2,2,5])
series3 = np.array([2,3,3,4])
index = np.arange(4)
plt.axis([0,15,-0.5,3.5])
plt.title('Diagram Batang Bertumpuk Multiserial')
plt.barh(index,series1,color='r')
plt.barh(index,series2,color='b',left=series1)
plt.barh(index,series3,color='g',left=(series2+series1))
plt.yticks(index+0.4,['Sep21','Okt21','Nov21','Des21'])
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x0 = np.arange(8)
y1 = np.array([4,3,2,1,2,4,6,6])
y2 = np.array([5,4,2,1,3,4,5,6])
plt.ylim(-7,7)
plt.bar(x0,y1,0.9,facecolor='r')
plt.bar(x0,-y2,0.9,facecolor='g')
plt.xticks(())
plt.grid(True)
for x, y in zip(x0,y1):
    plt.text(x + 0.4, y+0.05, '%d' % y, ha='center', va= 'bottom')
for x, y in zip(x0, y2):
    plt.text(x + 0.4, -y - 0.05, '%d' % y, ha='center', va= 'top')
plt.show()